# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1f6da8ec7598c2a96f245f3657152c1259ad71c6846ee26fca113c6829189ea0929031606e3479aa68ad8339913b2ade32d09073ca421884a9cfeda05a7a85

test:
  secret_key_base: 67389abb6ad2bf5bc996b2728286a6d57a2f40d7e5deca2f15b1e3cd5dabdb83f2f00da2b75f2bc28cbe9472f162eb5fcedc7c263a7c1b94e9d49ad2b2cedf3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
